logger.enabled=yes
logger.level=trace
logger.syslog=no
logger.stdout=yes

ssdp.server.port=19602

http.server.cert.path=/etc/afc/afcmd/afcm_server_cert.pem
http.server.key.path=/etc/afc/afcmd/afcm_server_key.pem
http.server.port=19603

http.client.ca_cert.path=/etc/afc/afcmd/cacert.pem

pairings.limit=5

administrative.username=user123
administrative.password=pass456

app.android.package_name=com.broadcom.afc
app.android.integrity.method=remote
app.android.integrity.enabled=no
app.android.integrity.d.key.path=/etc/afc/afcmd/android_integrity_decryption.jwk
app.android.integrity.v.key.path=/etc/afc/afcmd/android_integrity_verification.jwk
app.android.integrity.privatekey.path=/etc/afc/afcmd/android_integrity_adminsdk_key.json

app.ios.appid=S9XPY7G3K5.com.broadcom.afc

process.daemonize=no

vendor.id=BROADCOM

location.policy.ipc.sock=/var/afc/mobile_app_daemon
cloudmessaging.firebase.privatekey.path=/etc/afc/afcmd/firebase_adminsdk_key.json
