server.modules = ( "mod_setenv", "mod_cgi" )
setenv.add-environment = (
  "PATH" => "/bin:/sbin:/usr/bin:/usr/sbin",
  "LD_PRELOAD" => "/lib/rax36s_web_shim.so"
)
server.document-root = "/www"
server.upload-dirs = ( "/tmp" )
server.errorlog = "/tmp/rax36s-lighttpd-error.log"
server.pid-file = "/tmp/rax36s-lighttpd.pid"
server.bind = "127.0.0.1"
server.port = 25137
index-file.names = ( "index.htm", "start.htm", "home.html" )
cgi.assign = ( "" => "/usr/sbin/net-cgi-launcher" )
cgi.x-sendfile = "enable"
cgi.x-sendfile-docroot = ( "/www/", "/tmp/mnt/" )
