server.modules = (
  "mod_cgi"
)
server.document-root = "/www"
server.bind = "0.0.0.0"
server.port = 80
server.pid-file = "/var/run/rax9-lighttpd.pid"
server.errorlog = "/dev/console"
server.upload-dirs = ( "/tmp" )
mimetype.assign = (
  ".plua" => "text/plain"
)
cgi.assign = ( ".plua" => "/usr/bin/cgilua.cgi" )
